site_name: Deeplodocus Documentation
site_description: 'Documentation of Deeplodocus, Flexible and Modular Deep Learning Environment.'
site_url: http://deeplodocus.org
# google_analytics: ['UA-36723568-3', 'mkdocs.org']

repo_url: http://github.com/Deeplodocus/deeplodocus
edit_uri: http://github.com/Deeplodocus/deeplodocus

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - python

# theme: readthedocs
docs_dir: 'docs'

nav:
  - HOME: index.md
  - GETTING STARTED: getting_started.md
  - CONFIGURATION:
    - Main Configurations: configuration/config.md
    - Transformers: configuration/transformers.md
  - CREATING MODULES: creating_modules.md
  - EXISTING MODULES:
    - Data Sources: existing_modules/data_sources.md
    - Models: existing_modules/models.md
    - Losses: existing_modules/losses.md
    - Metrics: existing_modules/metrics.md
    - Transforms: existing_modules/transforms.md
    - Optimizers: existing_modules/optimizers.md
  - API: api.md
  - TUTORIALS: tutorials.md
  - ABOUT: about.md
