
#
# EVENT TYPES
#

DEEP_EVENT_UNDEFINED = 0
DEEP_EVENT_ON_BATCH_END = 1
DEEP_EVENT_ON_EPOCH_END = 2
DEEP_EVENT_ON_TRAINING_START = 3
DEEP_EVENT_ON_TRAINING_END = 4
DEEP_EVENT_ON_UPDATE_ALL = 5
DEEP_EVENT_ON_UPDATE_MODEL = 6
DEEP_EVENT_ON_UPDATE_OPTIMIZER = 7
DEEp_EVENT_ON_UPDATE_DATASET = 8
DEEP_EVENT_END_LISTENING = 9
DEEP_EVENT_OVERWATCH_METRIC_COMPUTED = 10
DEEP_EVENT_ON_EPOCH_START = 11
DEEP_EVENT_SAVING_REQUIRED = 12
DEEP_EVENT_SAVE_MODEL = 13